/*

 APPLE.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char Apple[] =
{
  0x00,0x10,0x00,0x08,0x76,0x7E,0xEF,0x99,
  0xDF,0x81,0xBD,0xC3,0x42,0x7E,0x3C,0x3C
};

/* End of APPLE.C */
