/*

 BANANA.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char Banana[] =
{
  0x20,0x30,0x70,0x50,0x70,0x50,0xB0,0xD0,
  0xB8,0xC8,0x9E,0xE6,0x4F,0x71,0x3E,0x3E
};

/* End of BANANA.C */
