/*

 SPIKE.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char Spike[] =
{
  0x08,0x08,0x5A,0x5A,0x24,0x3C,0xDA,0xE6,
  0x5B,0x67,0x24,0x3C,0x5A,0x5A,0x10,0x10
};

/* End of SPIKE.C */
